[env]
# Overrides the repo checkout location used by task scripts.
ATTRIBUTION_PIPELINE_CODE_DIR=/data/users/bob.potts/StateOfFires_2025-26/code

[template variables]
STATISTIC=['amplification']
# STATISTIC=['amplification', 'risk_ratio']
INDEX=['fwi']
# INDEX=['fwi', 'dsr']
METRIC=['p95']
# METRIC=['p95', '7x', 'cum']
HISTORICAL_SOURCE=['xclim', 'impacttb']
