[env]
# Overrides the repo checkout location used by task scripts.
ATTRIBUTION_PIPELINE_CODE_DIR=/data/users/bob.potts/StateOfFires_2025-26/code

[template variables]
COUNTRY=['Iberia', 'Chile', 'Canada']
# COUNTRY=['Iberia', 'Chile', 'Canada', 'Korea', 'Scotland']
BASELINE_MEMBER='1..15'
RUNTYPE=['hist', 'histnat']
INDEX=['fwi']
# INDEX=['fwi', 'dsr']
METRIC=['p95']
# METRIC=['p95', '7x', 'cum']
HISTORICAL_SOURCE=['xclim', 'impacttb']
